name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          8.*
          9.*
          10.*

    - name: Restore Packages
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore
